steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '--cache-from=${_REPO}/telefonnummernmerkspiel:latest'
      - '-t'
      - '${_REPO}/telefonnummernmerkspiel:latest'
      - '-t'
      - '${_REPO}/telefonnummernmerkspiel:$BUILD_ID'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REPO}/telefonnummernmerkspiel:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_BRANCH_NAME}" = "master" ]; then
          gcloud run deploy telefonnummernmerkspiel-prod --image ${_REPO}/telefonnummernmerkspiel:latest --region europe-west1 --project ${_PROJECT}
        else
          gcloud run deploy telefonnummernmerkspiel-dev --image ${_REPO}/telefonnummernmerkspiel:latest --region europe-west1 --project ${_PROJECT}
        fi

substitutions:
  _BRANCH_NAME: ${BRANCH_NAME}
  _PROJECT: ${PROJECT}
  _REPO: ${REPO}

images:
  - '${_REPO}/telefonnummernmerkspiel'

options:
  logging: CLOUD_LOGGING_ONLY